name = "contact-form"
main = "worker.js"
compatibility_date = "2024-10-09"

# Custom domain for your worker
routes = [
  { pattern = "contact-form.wileydigital.tech", custom_domain = true }
]

# Environment variables (set these in Cloudflare dashboard or via wrangler)
[vars]
# These will be set via Cloudflare dashboard for security

# For production, you'll need to set these secrets:
# wrangler secret put RESEND_API_KEY
# wrangler secret put CLOUDFLARE_ACCOUNT_ID  
# wrangler secret put CLOUDFLARE_API_TOKEN

# Or if using Cloudflare's native email routing:
# [env.production.vars]
# Add any non-sensitive configuration here
